export default {
	about: 'About',
	air_spading: 'Air Spading',
	why_us: 'Why Us',
	service_area: 'Service Area',
	services: 'Services',
	tree_removal: 'Tree Removal',
	tree_trimming: 'Tree Trimming',
	tree_planting: 'Tree Planting',
	arborist_consultation: 'Arborist Consultation',
	injection: 'Injection',
	cabling: 'Tree Cabling',
	more_services: 'Other Services',
	contact: 'Contact',
	soil_conditioning: 'Soil Conditioning',
}
